spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://ysu-team-002-dev.cnmgd1eiu1rn.ap-northeast-2.rds.amazonaws.com:3306/develop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false
        username: admin
        password: gemini02
        hikari:
            idleTimeout: 500
            connectionTimeout: 15000
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    mvc:
        view:
            prefix: /templates/
            suffix: .mustache
        log-request-details: true
        log-resolved-exception: true
    profiles:
        include:
            - oauth
            - API-KEY
    mail:
        host: smtp.gmail.com
        port: 587
        username: hajinkids3106
        password: ${mail.password}
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000 #(ms)
                    starttls:
                        enable: true
                    debug: true
                    ssl:
                        enable:

openai:
    api-key: ${openai.api-key}
    model: gpt-3.5-turbo
    api-url: https://api.openai.com/v1/chat/completions
    chat-model: ft:gpt-3.5-turbo-1106:verfit::8mMAWYWi
    sum-model: ft:gpt-3.5-turbo-1106:verfit::8mIJOkN0
    chat-system-prompt: "This model provides precise answers to legal proposal-related questions 
    using both the user-provided legal proposals and questions It processes dual inputs(question, legal proposal), 
    ensuring accurate, context-relevant responses in Korean. External references include a '(출처: [Source Name])'
     citation. For ambiguous inquiries, the model clarifies or assumes based on the legal context, explicitly stating 
     any assumptions.  Be sure to specify the correct reference. This model ensures comprehensive, relevant, 
     and accurate and well-founded answers in Korean."
    sum-system-prompt: "This is a legal proposal summary model. 
    This model generates a three-step summary (1. 제안 이유, 2. 주요 내용, 3. 세부 내용) in Korean 
    based on the legal proposal provided by the user.This model focuses on accuracy and avoids 
    adding information not present in the original text. The 'assistant' will summarize the 
    user-provided legal proposal, strictly adhering to the details in the text and avoiding 
    any assumptions or external information. The 'assistant' will summarize the main 
    contents of the legal proposal in 'three steps(1. 제안 이유, 2. 주요 내용, 3. 세부 내용)' in Korean."

logging:
    level:
        team:
            gemini: TRACE
        org:
            springframework:
                web:
                    filter:
                        CommonsRequestLoggingFilter: DEBUG
            hibernate:
                SQL: DEBUG
server:
    port: 8080