spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 498479298826-28h1oe9s96uhlo1k5pq0ovp7g2t9l50o.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
