spring:
    datasource:
        url: jdbc:mysql://localhost:8200/team_gemini_main?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useSSL=false
        username: root
        password: root
        hikari:
            idleTimeout: 500
            connectionTimeout: 15000
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    mvc:
        log-request-details: true
        log-resolved-exception: true
logging:
    level:
        team:
            gemini: TRACE
        org:
            springframework:
                web:
                    filter:
                        CommonsRequestLoggingFilter: DEBUG
            hibernate:
                SQL: DEBUG
server:
    port: 8080
