spring:
    datasource:
        url: jdbc:mysql://ysu-team-002-dev.cnmgd1eiu1rn.ap-northeast-2.rds.amazonaws.com:3306/develop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: admin
        password: gemini02
        hikari:
            idleTimeout: 500
            connectionTimeout: 15000
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    mvc:
        view:
            prefix: /templates/
            suffix: .mustache
        log-request-details: true
        log-resolved-exception: true
    profiles:
        include:
            - oauth
            - API-KEY
openai:
    api-key: "Api-key"
    model: gpt-3.5-turbo
    api-url: https://api.openai.com/v1/chat/completions
logging:
    level:
        team:
            gemini: TRACE
        org:
            springframework:
                web:
                    filter:
                        CommonsRequestLoggingFilter: DEBUG
            hibernate:
                SQL: DEBUG
server:
    port: 8080